export const ADD_MATCH = "ADD_MATCH";
export const DELETE_MATCH = "DELETE_MATCH";
export const GET_MATCHS = "GET_MATCHS";
export const GET_MATCH_SUCCESS = "GET_MATCH_SUCCESS";
export const DELETE_MATCH_SUCCESS = "DELETE_MATCH_SUCCESS";
